import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Springchat CMS",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden"> {/* Removed overflow-y-hidden */}
        {/* Fixed Navbar */}
        <div className="fixed top-0 left-0 right-0 z-50 bg-white border-b border-[#F1F5F9]">
          <Navbar />
        </div>

        {/* Sidebar + Main Content */}
        <div className="flex h-full pt-[80px]"> {/* Add top padding equal to navbar height */}
          <Sidebar />
          <main className="w-full overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
